# Generated by Django 2.2.4 on 2019-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setter', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('statement', models.CharField(max_length=100)),
                ('timelimit', models.IntegerField()),
                ('memorylimit', models.IntegerField()),
                ('score', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
