# Generated by Django 2.2.4 on 2019-08-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemsets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='setter',
            new_name='author',
        ),
    ]
