# Generated by Django 2.2.4 on 2019-08-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemsets', '0003_auto_20190809_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.TextField(default='', max_length=40000),
            preserve_default=False,
        ),
    ]
