# Generated by Django 2.2.4 on 2019-08-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python3', 'Python3')], max_length=10)),
                ('timetaken', models.IntegerField(default=500)),
                ('memorytaken', models.IntegerField(default=128)),
                ('code', models.TextField(max_length=40000)),
                ('status', models.CharField(default=-1, max_length=30)),
            ],
        ),
    ]
