# Generated by Django 2.2.4 on 2019-08-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0002_auto_20190809_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
